# SPDX-License-Identifier: GPL-2.0

ccflags-$(CONFIG_TCPC_CLASS) += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
ccflags-y += -I$(srctree)/drivers/power/supply/
obj-$(CONFIG_EXTCON_MTK_USB) += extcon-mtk-usb.o
